# Generated by Django 3.0.5 on 2020-10-04 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Order Date')),
                ('status', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Order Status')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Name')),
                ('title', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Title')),
                ('content', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Content')),
                ('pro_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Production Date')),
                ('number', models.IntegerField(blank=True, default=None, null=True, verbose_name='Number')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin-panel.Product')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin-panel.Order')),
            ],
        ),
    ]
